### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by AndroidGecko** [lohanidamodar/flutter_bottom_reveal#2]
no license at the moment in the repo

**Comment by joshua-hashimoto** [comment]
I love this widget so much.
It would be great if there is a license to this repo to know where I can use this widget :)

**Comment by lohanidamodar** [comment]
@dropscar @AndroidGecko sorry for late reply. I have added MIT license. Please feel free to use the package, as well as provide us feedback, suggestions, pull requests.
